### ISSUE TITLE
FastHandler的stack

### ISSUE THREAD

**Issue by shady831213** [YdrMaster/fast-trap#1]
Hi,
如果是工作在m-mode
https://github.com/YdrMaster/fast-trap/blob/65bf5df41bbf2ee65075f3434438f8259abb5c53/fast-trap/src/hal/riscv/mod.rs#L165
这里fast_handler是不能使用m-mode的栈的，可不可以让fast_handler是个naked函数，这样的话，可以做一个FastHandler的wrapper，在FastHandler前换回m-mode的栈，之后再恢复。这样的话，如果应用只工作再m-mode, fast_handler就可以利用m-mode的栈了。

https://github.com/shady831213/vfw_rs/blob/fast_trap/vfw_core/src/arch/rv/arch.rs#L104
这里我希望handler里可能还要处理一些其他的逻辑。。。如果不能使用本身m-mode的栈的话会有些麻烦。。。

**Comment by YdrMaster** [comment]
当然，可以随便改，我现在觉得这个库更多是举个例子……反正就是那些汇编，专门写的话总能改几条去几条。本来就是卷极限性能才要这么写的没必要非得套什么写法

**Comment by shady831213** [comment]
呃。。。这个crate不打算维护成一个比较通用的库是吗？只是当成一个example来show一下idea是不？

**Comment by YdrMaster** [comment]
其实原本确实是想维护的，然而我换组了😂现在实在没脑力想汇编了……你要是有兴趣我可以直接给你权限

**Comment by shady831213** [comment]
我也懒:joy:。。。没事。。。那回头我自己需要的话就直接fork了哈:smile:

**Comment by YdrMaster** [comment]
ok
